### ISSUE TITLE
Update wiki to link to the Github repository

### ISSUE THREAD

**Issue by gipi** [DangerousPrototypes/Bus_Pirate#2]
I'm an user of Bus Pirate and the main source of information is the [wiki](http://dangerousprototypes.com/docs/Bus_Pirate#Source) of the project that indicates as source repository the one on google code; lurking in the forum I found out that it's here now where development is done.

I don't know if it's the right place to complain, but would be great if the documentation was updated.

**Comment by saper-2** [comment]
2 months later... google links still up. I found too BP repo by digging through some topic on forum...

**Comment by n0skill** [comment]
The wiki seems updated now. Someone should close this issue.
