### ISSUE TITLE
DP Forums - Cant register: reCAPTCHA V1 IS SHUTDOWN

### ISSUE THREAD

**Issue by mikebdp2** [DangerousPrototypes/Bus_Pirate#9]
Dear Administrators, @vimark and @ian, I am writing to you with a really urgent matter. New members can't register at DangerousPrototypes forums, because

Confirmation of Registration:
reCAPTCHA V1 IS SHUTDOWN
Direct site owners to http://g.co/recaptcha/upgrade

You could try registering a new account by yourself, to easily see this problem. Please do something, maybe upgrade this captcha switch to the alternative domestic captcha to avoid depending on the stupid google

http://dangerousprototypes.com/forum/ucp.php?mode=register

Please read this thread - https://github.com/BusPirate/Bus_Pirate/issues/98 - btw it also describes the questions of DP collaboration with the community

**Comment by DangerousPrototypes** [comment]
Hey ya,

Im super sorry about the issue and I'm aware of it. Its on our list. Edward is working on it. Its really hard because phpbb is less than an ideal code base to work with. We need a path forward that will maintain current integration with the site. We also need akismet or similar spam filtering because phpbb is a spam magnet. If we upgrade phpbb then we loose our current home grown spam hammer filter. I also refuse to use the Google "choose the store fronts" "choose the street signs" because it is blocked in China and elsewhere, and also its so frustrating to use. 

⁣Cheers,

Ian

**Comment by DangerousPrototypes** [comment]
Part of that is everyone uses CDC hosted libraries (jquery, font awesome, bootstrap, Google fonts, etc) like life depends on them. Half these are blocked in China and time out and break web pages even if the page itself isn't blocked. It causes a huge amount of lag outside China too.

If you look at how we did dirtypcbs.com we use raw javascript when possible, and if we include a library we host it locally (out of nessesity). Buspirate.com is made the same way. 

I'm in Shenzhen at the moment running test batches of new hardware. I'll be back in Amsterdam on the 4th to start dealing with updates and community side. 

Thanks for liking what we do! It means a lot. We are hard at work readying the new stuff for fall. Getting all these emails today gives us lots of encouragement that someone will be interested in our progress.

⁣Cheers,

Ian

**Comment by mikebdp2** [comment]
@DangerousPrototypes Thank you very much to you and your team for fixing the captcha. This issue could be closed now...

**Comment by theolas** [comment]
@DangerousPrototypes Hi, sorry to bother, it seems like the site is not secured (expired certificate?) and the email validation emails are not reaching the mailboxes, so new accounts cannot be created.

**Comment by DangerousPrototypes** [comment]
Please try our new site forum.buspirate.com. I'm going to rip all the old DP sites to flatfile because the underlying tech is too old to migrate anywhere. Sorry for a very late reply, I think we touched bases on twitter too.
